import express from "express";
import {auth,authorizemanager,Adminauthorization} from "../middleware/auth.js";
import {createMovie,deletemovie,updatemovie,getallmovie,getmoviebyId,getCinemaDetails} from "../controllers/movie.js";
import { getallcinema } from "../controllers/cinema.js";
import { getcinemabyId } from "../controllers/screen.js";
const router=express.Router();
router.post('/movie',[auth,authorizemanager],createMovie);
router.patch('/movie/:id',[authorizemanager],updatemovie);
router.delete('/movie/:id',[authorizemanager],deletemovie);
router.get('/movie',getallmovie);
router.get('/movie/:id',getmoviebyId);
router.get('/movie/cinema/:id',getCinemaDetails);
export default router;
