import express from "express";
import {auth,Adminauthorization} from "../middleware/auth.js";
import {createscreen} from "../controllers/screen.js";
const router=express.Router();
router.post('/screen',[auth,Adminauthorization],createscreen);
// router.patch('/cinema/:id',[Adminauthorization],updatecinema);
// router.delete('/cinema/:id',[Adminauthorization],deletecinema);
// router.get('/cinema',getallcinema);
// router.get('/cinema/:id',getcinemabyId);
export default router;
